from __future__ import annotations

import json
from tempfile import TemporaryDirectory
from types import SimpleNamespace
import unittest

from email_delivery import build_summary_email, resend_summary_email, send_summary_email_for_meeting
from storage import MeetingStorage


def _settings(**updates):
    values = {
        "summary_email_enabled": True,
        "smtp_host": "smtp.example.com",
        "smtp_port": 587,
        "smtp_username": "bot@example.com",
        "smtp_password": "secret",
        "smtp_from": "MeetRead <bot@example.com>",
        "smtp_summary_recipients": ["alice@example.com", "bob@example.com"],
        "smtp_use_tls": True,
        "smtp_use_ssl": False,
        "smtp_timeout_seconds": 30,
        "smtp_subject_prefix": "[MeetRead]",
    }
    values.update(updates)
    return SimpleNamespace(**values)


def _metadata():
    return {
        "title": "Product Sync",
        "status": "completed",
        "duration_seconds": 120,
        "actual_join_time": "2026-05-26T10:00:00+00:00",
        "actual_leave_time": "2026-05-26T10:02:00+00:00",
        "transcript_file": "transcript_final.json",
        "meeting_intelligence_file": "meeting_intelligence.json",
        "meeting_intelligence_markdown_file": "meeting_intelligence.md",
        "audio_file": "audio_raw.wav",
        "audio_mp3_file": "audio_raw.mp3",
    }


def _intelligence():
    return {
        "summary": "The team reviewed launch status.",
        "key_points": [{"text": "Launch is on track.", "source_timestamp": "00:01:00", "source_speaker": "Alice"}],
        "decisions": [],
        "action_items": [{"task": "Send checklist", "owner": "Bob", "due_date": "by Friday"}],
        "risks": [],
        "blockers": [],
        "questions": [],
    }


class EmailDeliveryTests(unittest.TestCase):
    def test_build_summary_email_has_text_and_html_parts(self):
        message = build_summary_email("/tmp/meeting", _metadata(), _intelligence(), ["alice@example.com"], _settings())

        self.assertEqual(message["To"], "alice@example.com")
        self.assertIn("Product Sync summary", message["Subject"])
        payload = message.get_body(preferencelist=("plain",)).get_content()
        self.assertIn("The team reviewed launch status.", payload)
        self.assertIn("audio_raw.mp3", payload)
        self.assertIsNotNone(message.get_body(preferencelist=("html",)))

    def test_html_email_uses_structured_template(self):
        message = build_summary_email("/tmp/meeting", _metadata(), _intelligence(), ["alice@example.com"], _settings())

        html_body = message.get_body(preferencelist=("html",)).get_content()

        self.assertIn("MeetRead Summary", html_body)
        self.assertIn("Action Items", html_body)
        self.assertIn("<th", html_body)
        self.assertIn("Artifacts", html_body)
        self.assertIn("Generated by MeetRead AI", html_body)

    def test_html_email_escapes_user_content(self):
        metadata = {**_metadata(), "title": "<script>alert(1)</script>"}
        intelligence = {**_intelligence(), "summary": "Summary with <b>html</b>"}

        message = build_summary_email("/tmp/meeting", metadata, intelligence, ["alice@example.com"], _settings())
        html_body = message.get_body(preferencelist=("html",)).get_content()

        self.assertNotIn("<script>alert(1)</script>", html_body)
        self.assertIn("&lt;script&gt;alert(1)&lt;/script&gt;", html_body)
        self.assertIn("Summary with &lt;b&gt;html&lt;/b&gt;", html_body)

    def test_send_summary_email_uses_starttls_and_auth(self):
        fake = FakeSMTP()

        updates = send_summary_email_for_meeting(
            "/tmp/meeting",
            _metadata(),
            settings=_settings(),
            smtp_factory=lambda *args, **kwargs: fake,
        )

        self.assertEqual(updates["summary_email_status"], "sent")
        self.assertTrue(fake.started_tls)
        self.assertEqual(fake.login_args, ("bot@example.com", "secret"))
        self.assertEqual(len(fake.messages), 1)

    def test_send_summary_email_uses_ssl_factory(self):
        fake_ssl = FakeSMTP()

        updates = send_summary_email_for_meeting(
            "/tmp/meeting",
            _metadata(),
            settings=_settings(smtp_use_ssl=True, smtp_use_tls=True),
            smtp_factory=lambda *args, **kwargs: self.fail("plain SMTP should not be used"),
            smtp_ssl_factory=lambda *args, **kwargs: fake_ssl,
        )

        self.assertEqual(updates["summary_email_status"], "sent")
        self.assertFalse(fake_ssl.started_tls)
        self.assertEqual(len(fake_ssl.messages), 1)

    def test_send_summary_email_can_skip_auth(self):
        fake = FakeSMTP()

        updates = send_summary_email_for_meeting(
            "/tmp/meeting",
            _metadata(),
            settings=_settings(smtp_username="", smtp_password=""),
            smtp_factory=lambda *args, **kwargs: fake,
        )

        self.assertEqual(updates["summary_email_status"], "sent")
        self.assertIsNone(fake.login_args)

    def test_send_summary_email_disabled(self):
        updates = send_summary_email_for_meeting("/tmp/meeting", _metadata(), settings=_settings(summary_email_enabled=False))

        self.assertEqual(updates["summary_email_status"], "disabled")

    def test_send_summary_email_skips_without_recipients(self):
        updates = send_summary_email_for_meeting(
            "/tmp/meeting",
            _metadata(),
            settings=_settings(smtp_summary_recipients=[]),
        )

        self.assertEqual(updates["summary_email_status"], "skipped_no_recipients")

    def test_send_summary_email_records_failure(self):
        updates = send_summary_email_for_meeting(
            "/tmp/meeting",
            _metadata(),
            settings=_settings(),
            smtp_factory=lambda *args, **kwargs: FailingSMTP(),
        )

        self.assertEqual(updates["summary_email_status"], "failed")
        self.assertIn("SMTP unavailable", updates["summary_email_error"])

    def test_resend_summary_email_updates_metadata(self):
        with TemporaryDirectory() as tmp:
            storage = MeetingStorage(tmp)
            meeting_dir = storage.create_meeting_dir("Product Sync")
            storage.write_metadata(meeting_dir, _metadata())
            (meeting_dir / "meeting_intelligence.json").write_text(json.dumps(_intelligence()), encoding="utf-8")

            updates = resend_summary_email(meeting_dir, settings=_settings(), smtp_factory=lambda *args, **kwargs: FakeSMTP())
            metadata = storage.read_metadata(meeting_dir)

            self.assertEqual(updates["summary_email_status"], "sent")
            self.assertEqual(metadata["summary_email_status"], "sent")


class FakeSMTP:
    def __init__(self):
        self.started_tls = False
        self.login_args = None
        self.messages = []

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def starttls(self):
        self.started_tls = True

    def login(self, username, password):
        self.login_args = (username, password)

    def send_message(self, message):
        self.messages.append(message)


class FailingSMTP(FakeSMTP):
    def send_message(self, message):
        raise RuntimeError("SMTP unavailable")


if __name__ == "__main__":
    unittest.main()
